# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-24 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[(b'http', b'http'), (b'http2', b'http2'), (b'socks4', b'socks4'), (b'socks5', b'socks5')], max_length=10, verbose_name=b'Scheme')),
                ('username', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'Username')),
                ('password', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'Password')),
                ('host', models.CharField(max_length=50, verbose_name=b'Host')),
                ('port', models.IntegerField(verbose_name=b'Port')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.IntegerField(verbose_name=b'Frontend ID')),
                ('submitted_on', models.DateTimeField(blank=True, default=main.models.add_now, verbose_name=b'Submitted on')),
                ('started_on', models.DateTimeField(blank=True, default=None, null=True, verbose_name=b'Started on')),
                ('completed_on', models.DateTimeField(blank=True, default=None, null=True, verbose_name=b'Completed on')),
                ('status', models.IntegerField(blank=True, default=0, verbose_name=b'Status')),
                ('object_id', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name=b'ObjectID')),
                ('url', models.CharField(max_length=4096, verbose_name=b'Target URL')),
                ('referer', models.CharField(blank=True, default=None, max_length=4096, null=True, verbose_name=b'Referer')),
                ('useragent', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'User Agent')),
                ('events', models.CharField(blank=True, default=None, max_length=4096, null=True, verbose_name=b'Specified DOM events handling')),
                ('delay', models.IntegerField(blank=True, default=None, null=True, verbose_name=b'Maximum setTimeout/setInterval delay (milliseconds)')),
                ('timeout', models.IntegerField(blank=True, default=None, null=True, verbose_name=b'Analysis timeout (seconds)')),
                ('threshold', models.IntegerField(blank=True, default=None, null=True, verbose_name=b'Maximum pages to fetch')),
                ('no_cache', models.BooleanField(default=False, verbose_name=b'Disable local web cache')),
                ('extensive', models.BooleanField(default=False, verbose_name=b'Extensive fetch on linked pages')),
                ('broken_url', models.BooleanField(default=False, verbose_name=b'Broken URL mode')),
                ('verbose', models.BooleanField(default=False, verbose_name=b'Verbose mode')),
                ('quiet', models.BooleanField(default=False, verbose_name=b'Quiet (disable console logging)')),
                ('debug', models.BooleanField(default=False, verbose_name=b'Debug mode')),
                ('ast_debug', models.BooleanField(default=False, verbose_name=b'AST debug mode (requires Debug mode)')),
                ('http_debug', models.BooleanField(default=False, verbose_name=b'HTTP debug mode')),
                ('vtquery', models.BooleanField(default=False, verbose_name=b'Query VirusTotal for samples')),
                ('vtsubmit', models.BooleanField(default=False, verbose_name=b'Submit samples to VirusTotal')),
                ('no_honeyagent', models.BooleanField(default=False, verbose_name=b'Disable HoneyAgent support')),
                ('adobepdf', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name=b'Adobe Acrobat Reader version (default: 9.1.0)')),
                ('no_adobepdf', models.BooleanField(default=False, verbose_name=b'Disable Adobe Acrobat Reader plugin')),
                ('shockwave', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name=b'Shockwave Flash version (default: 10.0.64.0)')),
                ('no_shockwave', models.BooleanField(default=False, verbose_name=b'Disable Shockwave Flash plugin')),
                ('javaplugin', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name=b'Java plugin version (default: 1.6.0.32)')),
                ('no_javaplugin', models.BooleanField(default=False, verbose_name=b'Enable/ Disable Java plugin')),
                ('proxy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Proxy')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
